/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ai.kitt.snowboy;

public class snowboy {
    public enum  MsgEnum {
        MSG_VAD_END,
        MSG_VAD_NOSPEECH,
        MSG_VAD_SPEECH,
        MSG_VOLUME_NOTIFY,
        MSG_WAV_DATAINFO,
        MSG_RECORD_START,
        MSG_RECORD_STOP,
        MSG_ACTIVE,
        MSG_ERROR,
        MSG_INFO;

        public static MsgEnum getMsgEnum(int i) {
            return MsgEnum.values()[i];
        }
    }
}